#!/usr/bin/env bash
set -euo pipefail

# changelog.sh — Generate a structured CHANGELOG.md from git history
# Usage: bash scripts/changelog.sh [--repo /path/to/repo] [--output CHANGELOG.md]

REPO_DIR="${PWD}"
OUTPUT_FILE="${REPO_DIR}/CHANGELOG.md"
SINCE_TAG=""

# Parse args
while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO_DIR="$2"; shift 2 ;;
    --output) OUTPUT_FILE="$2"; shift 2 ;;
    --since) SINCE_TAG="$2"; shift 2 ;;
    *) echo "Usage: $0 [--repo <path>] [--output <file>] [--since <tag>]"; exit 1 ;;
  esac
done

if ! git -C "$REPO_DIR" rev-parse --git-dir > /dev/null 2>&1; then
  echo "Error: $REPO_DIR is not a git repository"
  exit 1
fi

# Determine the tag/range to start from
if [[ -z "$SINCE_TAG" ]]; then
  LATEST_TAG=$(git -C "$REPO_DIR" describe --tags --abbrev=0 2>/dev/null || echo "")
  if [[ -n "$LATEST_TAG" ]]; then
    SINCE_TAG="$LATEST_TAG"
    RANGE="${SINCE_TAG}..HEAD"
  else
    RANGE="HEAD"
  fi
else
  RANGE="${SINCE_TAG}..HEAD"
fi

# Get the project name
PROJECT_NAME=$(basename "$(git -C "$REPO_DIR" config --get remote.origin.url 2>/dev/null || echo "$REPO_DIR")" .git)

# Build an associative-array-like structure for categorized commits
ADDED=()
FIXED=()
CHANGED=()
REMOVED=()
OTHER=()

# Date of first commit in range
if [[ "$RANGE" == "HEAD" ]]; then
  COMMIT_LOG=$(git -C "$REPO_DIR" log --oneline --reverse HEAD)
  FIRST_DATE=$(git -C "$REPO_DIR" log --reverse --format="%ad" --date=short HEAD 2>/dev/null | head -1)
  LAST_DATE=$(git -C "$REPO_DIR" log --format="%ad" --date=short HEAD 2>/dev/null | head -1)
else
  COMMIT_LOG=$(git -C "$REPO_DIR" log --oneline --reverse "$RANGE")
  FIRST_DATE=$(git -C "$REPO_DIR" log --reverse --format="%ad" --date=short "$RANGE" 2>/dev/null | head -1)
  LAST_DATE=$(git -C "$REPO_DIR" log --format="%ad" --date=short "$RANGE" 2>/dev/null | head -1)
fi

# Categorize each commit
while IFS= read -r line; do
  COMMIT_HASH=$(echo "$line" | awk '{print $1}')
  COMMIT_MSG=$(echo "$line" | cut -d' ' -f2-)

  # Normalize for categorization
  LOWER_MSG=$(echo "$COMMIT_MSG" | tr '[:upper:]' '[:lower:]')

  # Check conventional commit prefixes
  if echo "$LOWER_MSG" | grep -qE '^(feat|feature|add|implement|create)'; then
    ADDED+=("${COMMIT_MSG}")
  elif echo "$LOWER_MSG" | grep -qE '^(fix|bugfix|hotfix|patch|correct)'; then
    FIXED+=("${COMMIT_MSG}")
  elif echo "$LOWER_MSG" | grep -qE '^(change|update|refactor|perf|improve|migrate|bump)'; then
    CHANGED+=("${COMMIT_MSG}")
  elif echo "$LOWER_MSG" | grep -qE '^(remove|drop|deprecate|delete|clean)'; then
    REMOVED+=("${COMMIT_MSG}")
  else
    OTHER+=("${COMMIT_MSG}")
  fi
done <<< "$COMMIT_LOG"

# Generate CHANGELOG.md
{
  echo "# Changelog"
  echo ""
  echo "## [Unreleased]"
  if [[ -n "$FIRST_DATE" ]]; then
    echo "> Commits from ${FIRST_DATE} to ${LAST_DATE:-$FIRST_DATE}"
  fi
  echo ""

  if [[ ${#ADDED[@]} -gt 0 ]]; then
    echo "### Added"
    for item in "${ADDED[@]}"; do
      echo "- ${item}"
    done
    echo ""
  fi

  if [[ ${#FIXED[@]} -gt 0 ]]; then
    echo "### Fixed"
    for item in "${FIXED[@]}"; do
      echo "- ${item}"
    done
    echo ""
  fi

  if [[ ${#CHANGED[@]} -gt 0 ]]; then
    echo "### Changed"
    for item in "${CHANGED[@]}"; do
      echo "- ${item}"
    done
    echo ""
  fi

  if [[ ${#REMOVED[@]} -gt 0 ]]; then
    echo "### Removed"
    for item in "${REMOVED[@]}"; do
      echo "- ${item}"
    done
    echo ""
  fi

  if [[ ${#OTHER[@]} -gt 0 ]]; then
    echo "### Other"
    for item in "${OTHER[@]}"; do
      echo "- ${item}"
    done
    echo ""
  fi

  echo "---"
  echo "_Generated by [changelog.sh](scripts/changelog.sh)_"
} > "$OUTPUT_FILE"

echo "✅ CHANGELOG generated: ${OUTPUT_FILE}"
echo "   $((${#ADDED[@]} + ${#FIXED[@]} + ${#CHANGED[@]} + ${#REMOVED[@]} + ${#OTHER[@]})) commits categorized"
